"""initial schema

Revision ID: 78e4764af7b0
Revises:
Create Date: 2026-03-02 18:59:58.654758

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '78e4764af7b0'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('glassdoor_url', sa.String(), nullable=True),
    sa.Column('research_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('company_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('resume_profiles',
    sa.Column('resume_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('key_skills', sa.Text(), nullable=False),
    sa.Column('experience_summary', sa.Text(), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('resume_id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('scraper_runs',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scraper_name', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('jobs_new', sa.Integer(), nullable=False),
    sa.Column('jobs_updated', sa.Integer(), nullable=False),
    sa.Column('pages_scraped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('config_snapshot', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('raw_job_postings',
    sa.Column('raw_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('salary_raw', sa.String(), nullable=True),
    sa.Column('location_raw', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('scraper_run_id', sa.Integer(), nullable=True),
    sa.Column('fingerprint_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['scraper_run_id'], ['scraper_runs.run_id'], ),
    sa.PrimaryKeyConstraint('raw_id')
    )
    with op.batch_alter_table('raw_job_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_job_postings_fingerprint_hash'), ['fingerprint_hash'], unique=False)

    op.create_table('processed_jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('raw_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('location_policy', sa.String(), nullable=False),
    sa.Column('remote_regions', sa.Text(), nullable=True),
    sa.Column('description_clean', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('application_url', sa.String(), nullable=False),
    sa.Column('source_site', sa.String(), nullable=False),
    sa.Column('fingerprint_hash', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['raw_id'], ['raw_job_postings.raw_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('processed_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_jobs_fingerprint_hash'), ['fingerprint_hash'], unique=True)
        batch_op.create_index('ix_processed_jobs_source_first_seen', ['source_site', 'first_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_jobs_status'), ['status'], unique=False)

    op.create_table('application_statuses',
    sa.Column('status_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processed_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('status_id')
    )
    with op.batch_alter_table('application_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_statuses_job_id'), ['job_id'], unique=False)

    op.create_table('cover_letters',
    sa.Column('letter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processed_jobs.job_id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_profiles.resume_id'], ),
    sa.PrimaryKeyConstraint('letter_id')
    )
    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cover_letters_job_id'), ['job_id'], unique=False)

    op.create_table('filter_results',
    sa.Column('filter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('raw_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('rules_applied', sa.Text(), nullable=False),
    sa.Column('rules_passed', sa.Text(), nullable=False),
    sa.Column('rules_failed', sa.Text(), nullable=False),
    sa.Column('rule_details', sa.Text(), nullable=True),
    sa.Column('filtered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processed_jobs.job_id'], ),
    sa.ForeignKeyConstraint(['raw_id'], ['raw_job_postings.raw_id'], ),
    sa.PrimaryKeyConstraint('filter_id')
    )
    op.create_table('job_fingerprints',
    sa.Column('fingerprint_hash', sa.String(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_urls', sa.Text(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processed_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('fingerprint_hash')
    )
    op.create_table('match_evaluations',
    sa.Column('eval_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('tier_evaluated', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('fit_category', sa.String(), nullable=True),
    sa.Column('skill_match_score', sa.Integer(), nullable=True),
    sa.Column('seniority_match_score', sa.Integer(), nullable=True),
    sa.Column('remote_compatibility_score', sa.Integer(), nullable=True),
    sa.Column('salary_alignment_score', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('flags', sa.Text(), nullable=True),
    sa.Column('recommended_resume_id', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('cover_letter_hints', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processed_jobs.job_id'], ),
    sa.ForeignKeyConstraint(['recommended_resume_id'], ['resume_profiles.resume_id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_profiles.resume_id'], ),
    sa.PrimaryKeyConstraint('eval_id')
    )
    with op.batch_alter_table('match_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_evaluations_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_match_evaluations_job_resume', ['job_id', 'resume_id'], unique=False)

    op.create_table('why_company_answers',
    sa.Column('answer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processed_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    with op.batch_alter_table('why_company_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_why_company_answers_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('why_company_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_why_company_answers_job_id'))

    op.drop_table('why_company_answers')
    with op.batch_alter_table('match_evaluations', schema=None) as batch_op:
        batch_op.drop_index('ix_match_evaluations_job_resume')
        batch_op.drop_index(batch_op.f('ix_match_evaluations_job_id'))

    op.drop_table('match_evaluations')
    op.drop_table('job_fingerprints')
    op.drop_table('filter_results')
    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cover_letters_job_id'))

    op.drop_table('cover_letters')
    with op.batch_alter_table('application_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_statuses_job_id'))

    op.drop_table('application_statuses')
    with op.batch_alter_table('processed_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_jobs_status'))
        batch_op.drop_index('ix_processed_jobs_source_first_seen')
        batch_op.drop_index(batch_op.f('ix_processed_jobs_fingerprint_hash'))

    op.drop_table('processed_jobs')
    with op.batch_alter_table('raw_job_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_job_postings_fingerprint_hash'))

    op.drop_table('raw_job_postings')
    op.drop_table('scraper_runs')
    op.drop_table('resume_profiles')
    op.drop_table('companies')
    # ### end Alembic commands ###
