"""M3.5: Remove user-action values from ProcessedJob.status CheckConstraint.

User-action states (shortlisted, rejected_by_user, applied) now live
exclusively in DS7 ApplicationStatus. ProcessedJob.status tracks pipeline
stages only.

Revision ID: d4e5f6a7b8c9
Revises: c3d4e5f6a7b8
Create Date: 2026-03-08
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers
revision = "d4e5f6a7b8c9"
down_revision = "c3d4e5f6a7b8"
branch_labels = None
depends_on = None

# Old constraint included user-action values
_OLD_VALUES = (
    "status IN ('new', 'tier1_pass', 'tier1_fail', 'tier1_ambiguous', 'tier2_pass', "
    "'tier2_fail', 'tier2_maybe', 'tier2_error', 'evaluated', 'shortlisted', "
    "'rejected_by_user', 'applied')"
)

# New constraint: pipeline stages only
_NEW_VALUES = (
    "status IN ('new', 'tier1_pass', 'tier1_fail', 'tier1_ambiguous', 'tier2_pass', "
    "'tier2_fail', 'tier2_maybe', 'tier2_error', 'evaluated')"
)


def upgrade() -> None:
    # Clean any existing rows that have user-action statuses
    op.execute(
        sa.text(
            "UPDATE processed_jobs SET status = 'evaluated' "
            "WHERE status IN ('shortlisted', 'rejected_by_user', 'applied')"
        )
    )

    # PostgreSQL: drop old constraint, add new one
    # The constraint name is auto-generated by SQLAlchemy; find it dynamically
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            "SELECT conname FROM pg_constraint "
            "WHERE conrelid = 'processed_jobs'::regclass "
            "AND contype = 'c' "
            "AND pg_get_constraintdef(oid) LIKE '%shortlisted%'"
        )
    )
    for row in result:
        op.drop_constraint(row[0], "processed_jobs", type_="check")

    op.create_check_constraint(
        "ck_processed_jobs_status",
        "processed_jobs",
        _NEW_VALUES,
    )


def downgrade() -> None:
    op.drop_constraint("ck_processed_jobs_status", "processed_jobs", type_="check")
    op.create_check_constraint(
        "ck_processed_jobs_status_old",
        "processed_jobs",
        _OLD_VALUES,
    )
